name: integracion_continua
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Esta tarea (job) fue lanzado automaticamente por el evento ${{ github.event_name }}"
      - run: echo "ğŸ§ Esta tarea esta corriendo en un servidor ${{ runner.os }} por GitHub!"
      - run: echo "ğŸ” El nombre de la rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
      - name: Descargando el codigo
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado."
      - run: echo "ğŸ–¥ï¸ El workflow esta listo para testear el codigo"
      - name: Corriendo las pruebas
        run: |
          mvn clean test
      - run: echo "ğŸ El estado de la tarea es ${{ job.status }}."
