name: integracion_continua

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  Explore-GitHub-Actions:
    name: ${{ github.actor }} estÃ¡ probando GitHub Actions ğŸš€
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el cÃ³digo
        uses: actions/checkout@v3

      - run: echo "ğŸ’¡ El repositorio ha sido clonado."
      - run: echo "ğŸ–¥ï¸ Listo para testear el cÃ³digo"

      - name: Pruebas unitarias
        run: mvn clean test

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build del proyecto
        run: mvn clean package

      - name: Levantar entorno con docker-compose
        run: docker-compose up -d

      - name: Ejecutar pruebas E2E
        run: mvn test -Dtest="*E2E"

      - name: Detener servicios
        if: always()
        run: docker-compose down

      - run: echo "ğŸ Estado final del job: ${{ job.status }}"
